global:
  # -- (string) Primary domain used across applications
  # @default -- "noty.cc"
  domain: noty.cc

  # -- (map) Configuration for cert-manager
  certManager:
    # -- (string) Default cert-manager cluster issuer
    # @default -- "cloudflare-cluster-issuer"
    clusterIssuer: cloudflare-cluster-issuer

  # -- (map) Configuration for ExternalDNS
  externalDns:
    # -- (string) DNS provider for external-dns
    # @default -- "cloudflare"
    provider: cloudflare

    # -- (string) ACME server environment, `production` or `staging`
    # @default -- "production"
    acmeServer: production
